apiVersion: batch/v1
kind: CronJob
metadata:
  name: randomizer
spec:
  schedule: "30 8-21/* * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: randomizer
            image: ghcr.io/mreider/loadgenerator:168
            command:
            - /bin/sh
            - -c
            - bash 
            - cron.sh
            env:
            - name: FRONTEND_ADDR
              value: "34.132.236.107:80"
            - name: USERS
              value: "1000"
          restartPolicy: OnFailure