apiVersion: batch/v1
kind: CronJob
metadata:
  name: randomizer
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: randomizer
            image: ghcr.io/mreider/loadgenerator:150
            command:
            - /bin/sh
            - -c
            - bash 
            - cron.sh
            env:
            - name: FRONTEND_ADDR
              value: "frontend:80"
            - name: USERS
              value: "10000"
          restartPolicy: OnFailure