on: 
  push:
     branches:
       - master
  workflow_dispatch:
jobs:
  build-and-publish:
    name: Build and push images, bump versions in yaml files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appname: 
          - emailservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - checkoutservice
          - paymentservice
          - currencyservice
          - cartservice
          - frontend
          - adservice
          - loadgenerator
    steps:
      - name: run number with offset
        env:
            NUM: ${{ github.run_number }}
            ACTIONS_ALLOW_UNSECURE_COMMANDS: True
        run: |
            echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+15))
      - uses: actions/checkout@v2.3.2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build & push ${{ matrix.appname }}
        with:
          image: ${{ matrix.appname }}
          tags: ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}, latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 
          directory: ./src/${{ matrix.appname == 'cartservice' && 'cartservice/src/' ||  matrix.appname }}  
          dockerfile: ./src/${{ matrix.appname == 'cartservice' && 'cartservice/src/' ||  matrix.appname }}/Dockerfile
  deploy:
    needs: [build-and-publish]
    runs-on: ubuntu-latest
    steps:
      - name: run number with offset
        env:
            NUM: ${{ github.run_number }}
            ACTIONS_ALLOW_UNSECURE_COMMANDS: True
            PROJECT_ID: ${{ secrets.GKE_PROJECT }}
        run: |
            echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+15))
      - uses: actions/checkout@v2.3.2
        name: Check out code
      - name: Update deployment file (staging)
        run: |
          find ./dynatrace/kubernetes_templates -type f -name '*.yaml' -exec sed -i 's|<TAG>|'${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}'|' {} \;
          cp -rf dynatrace/kubernetes_templates/. dynatrace/kubernetes_autogenerated/
      - name: Update deployment files
        uses: test-room-7/action-update-file@v1
        with:
          file-path: dynatrace/kubernetes_autogenerated/*.yaml
          commit-msg: Bump version to ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup gcloud cli
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: set kubernetes context
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: microservices-demo-mreider
          location: us-central1-c
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: Deploy
        run: |-
          kubectl apply -f dynatrace/kubernetes_autogenerated -n hipster
